import { FormEvent, useCallback, useState } from 'react'
import { Plus, X } from 'lucide-react'
import { db } from '../db'
import { useData } from '../lib/useData'
import { getDeviceId, newId } from '../lib/ids'
import { saveRefiningBatch } from '../lib/repository'
import { Card, Empty, PageHeader } from '../components/UI'
import { D } from '../lib/money'

export function Refining(){
  const loader=useCallback(()=>db.refining.orderBy('updatedAt').reverse().toArray(),[]);const {data,refresh}=useData(loader,[]);const [show,setShow]=useState(false);const [inputWeight,setInputWeight]=useState('0');const [inputPurity,setInputPurity]=useState('925');const [charge,setCharge]=useState('0');const [refiner,setRefiner]=useState('');const [notes,setNotes]=useState('')
  const submit=async(e:FormEvent)=>{e.preventDefault();if(Number(inputWeight)<=0)return alert('أدخل وزن الإدخال');const now=new Date().toISOString();const id=newId();await saveRefiningBatch({id,batchNo:`REF-${id.slice(0,7).toUpperCase()}`,refiningStatus:'open',inputWeight,inputPurity,refiningCharge:charge,refinerName:refiner||undefined,notes,createdAt:now,updatedAt:now,version:1,archived:false,syncStatus:'pending',deviceId:getDeviceId()});setShow(false);setInputWeight('0');setNotes('');refresh()}
  const closeBatch=async(r:any)=>{const outputWeight=prompt('وزن الناتج؟',r.outputWeight||'0');if(outputWeight===null)return;const outputPurity=prompt('عيار الناتج؟',r.outputPurity||'999');if(outputPurity===null)return;const inputPure=D(r.inputWeight).mul(r.inputPurity).div(1000);const outputPure=D(outputWeight).mul(outputPurity).div(1000);const loss=inputPure.sub(outputPure);await saveRefiningBatch({...r,refiningStatus:'closed',outputWeight,outputPurity,lossWeight:loss.toFixed(3),receivedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),version:r.version+1,syncStatus:'pending',deviceId:getDeviceId()});refresh()}
  return <><PageHeader title="الكسر والتصفية" description="تتبع الدفعات ووزن الإدخال والناتج والفقد وأجرة التصفية" actions={<button className="btn primary" onClick={()=>setShow(true)}><Plus size={17}/> دفعة جديدة</button>}/><Card>{data.length?<div className="table-wrap"><table><thead><tr><th>الدفعة</th><th>إدخال</th><th>عيار الإدخال</th><th>الناتج</th><th>الفقد الخالص</th><th>المصفّي</th><th>الحالة</th><th></th></tr></thead><tbody>{data.map(r=><tr key={r.id}><td><b>{r.batchNo}</b></td><td>{r.inputWeight} غ</td><td>{r.inputPurity}</td><td>{r.outputWeight?`${r.outputWeight} غ / ${r.outputPurity}`:'—'}</td><td>{r.lossWeight||'—'}</td><td>{r.refinerName||'—'}</td><td>{r.refiningStatus}</td><td>{r.refiningStatus!=='closed'&&<button className="btn small" onClick={()=>closeBatch(r)}>إغلاق الدفعة</button>}</td></tr>)}</tbody></table></div>:<Empty/>}</Card>{show&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><h3>دفعة كسر/تصفية</h3><button type="button" className="icon-btn" onClick={()=>setShow(false)}><X/></button></div><div className="form-grid"><label className="field"><span>وزن الإدخال</span><input type="number" step="0.001" value={inputWeight} onChange={e=>setInputWeight(e.target.value)}/></label><label className="field"><span>عيار الإدخال</span><input type="number" step="0.001" value={inputPurity} onChange={e=>setInputPurity(e.target.value)}/></label><label className="field"><span>أجرة التصفية</span><input type="number" step="0.01" value={charge} onChange={e=>setCharge(e.target.value)}/></label><label className="field"><span>المصفّي</span><input value={refiner} onChange={e=>setRefiner(e.target.value)}/></label></div><label className="field"><span>ملاحظات</span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="btn primary wide">حفظ الدفعة أوفلاين</button></form></div>}</>
}
