import { FormEvent, useCallback, useMemo, useState } from 'react'
import { ClipboardCheck, Plus, X } from 'lucide-react'
import { db } from '../db'
import { useData } from '../lib/useData'
import { getDeviceId, newId } from '../lib/ids'
import { saveStocktake } from '../lib/repository'
import { Card, Empty, PageHeader } from '../components/UI'
import type { StocktakeLine } from '../types'

export function Stocktake(){
  const loader=useCallback(async()=>({rows:await db.stocktakes.orderBy('completedAt').reverse().toArray(),items:(await db.silverItems.toArray()).filter(x=>!x.archived&&x.status==='available')}),[])
  const {data,refresh}=useData(loader,{rows:[],items:[]} as Awaited<ReturnType<typeof loader>>)
  const [show,setShow]=useState(false);const [notes,setNotes]=useState('');const [lines,setLines]=useState<StocktakeLine[]>([])
  const start=()=>{setLines(data.items.map(i=>({id:newId(),itemId:i.id,sku:i.sku,name:i.name,expectedQuantity:String(i.quantity||1),countedQuantity:String(i.quantity||1),expectedWeight:i.netWeight,countedWeight:i.netWeight,quantityDifference:'0',weightDifference:'0',approved:true})));setNotes('');setShow(true)}
  const update=(id:string,key:'countedQuantity'|'countedWeight'|'reason',value:string)=>setLines(ls=>ls.map(l=>{if(l.id!==id)return l;const n={...l,[key]:value};n.quantityDifference=String(Number(n.countedQuantity||0)-Number(n.expectedQuantity||0));n.weightDifference=(Number(n.countedWeight||0)-Number(n.expectedWeight||0)).toFixed(3);n.approved=Math.abs(Number(n.quantityDifference))<0.0001&&Math.abs(Number(n.weightDifference))<0.0005?true:Boolean(n.reason?.trim());return n}))
  const diffs=useMemo(()=>lines.filter(l=>Math.abs(Number(l.quantityDifference))>0.0001||Math.abs(Number(l.weightDifference))>0.0005),[lines])
  const submit=async(e:FormEvent)=>{e.preventDefault();if(diffs.some(x=>!x.reason?.trim()))return alert('كل فرق بالجرد يحتاج سبب قبل الاعتماد');const now=new Date().toISOString();const id=newId();await saveStocktake({id,reference:`STK-${now.slice(0,10).replaceAll('-','')}-${id.slice(0,5).toUpperCase()}`,stocktakeStatus:'completed',startedAt:now,completedAt:now,notes,lines,createdAt:now,updatedAt:now,version:1,archived:false,syncStatus:'pending',deviceId:getDeviceId()});setShow(false);refresh()}
  return <>
    <PageHeader title="الجرد" description="جرد فعلي بالقطعة والوزن مع توثيق كل فرق وسببه وحفظه أوفلاين" actions={<button className="btn primary" onClick={start}><Plus size={17}/> جرد جديد</button>}/>
    <div className="stats-grid compact"><div className="stat"><span>قطع متاحة للجرد</span><strong>{data.items.length}</strong></div><div className="stat"><span>جردات محفوظة</span><strong>{data.rows.length}</strong></div><div className="stat"><span>آخر جرد</span><strong>{data.rows[0]?new Date(data.rows[0].completedAt).toLocaleDateString('ar'):'—'}</strong></div><div className="stat"><span>معلّق للمزامنة</span><strong>{data.rows.filter(x=>x.syncStatus!=='synced').length}</strong></div></div>
    <Card className="mt">{data.rows.length?<div className="table-wrap"><table><thead><tr><th>المرجع</th><th>التاريخ</th><th>القطع</th><th>الفروقات</th><th>الحالة</th><th>التفاصيل</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.id}><td><b>{r.reference}</b></td><td>{new Date(r.completedAt).toLocaleString('ar')}</td><td>{r.lines.length}</td><td>{r.lines.filter(l=>Number(l.quantityDifference)!==0||Number(l.weightDifference)!==0).length}</td><td><span className={`badge ${r.syncStatus}`}>{r.syncStatus}</span></td><td><details><summary className="btn small">عرض التفاصيل</summary><div style={{minWidth:320,paddingTop:8}}>{r.lines.map(l=><div key={l.id} style={{padding:'8px 0',borderBottom:'1px solid var(--border)'}}><b>{l.sku||'—'} • {l.name||'—'}</b><div>العدد: {l.expectedQuantity} متوقع / {l.countedQuantity} فعلي / الفرق {Number(l.quantityDifference).toFixed(3)}</div><div>الوزن: {l.expectedWeight} غ متوقع / {l.countedWeight} غ فعلي / <span className={Number(l.weightDifference)!==0?'text-danger':''}>الفرق {Number(l.weightDifference).toFixed(3)} غ</span></div><div>السبب: {l.reason||'—'}</div></div>)}</div></details></td></tr>)}</tbody></table></div>:<Empty/>}</Card>
    {show&&<div className="modal-backdrop"><form className="modal modal-wide" onSubmit={submit}><div className="modal-head"><h3>جرد المخزون الحالي</h3><button type="button" className="icon-btn" onClick={()=>setShow(false)}><X/></button></div><div className="notice info"><ClipboardCheck size={17}/> أي فرق في العدد أو الوزن يتطلب كتابة سبب قبل اعتماد الجرد.</div><div className="table-wrap stocktake-table"><table><thead><tr><th>SKU</th><th>القطعة</th><th>متوقع عدد</th><th>فعلي عدد</th><th>متوقع وزن</th><th>فعلي وزن</th><th>فرق الوزن</th><th>السبب</th></tr></thead><tbody>{lines.map(l=><tr key={l.id}><td>{l.sku}</td><td>{l.name}</td><td>{l.expectedQuantity}</td><td><input className="table-input" type="number" step="1" value={l.countedQuantity} onChange={e=>update(l.id,'countedQuantity',e.target.value)}/></td><td>{l.expectedWeight}</td><td><input className="table-input" type="number" step="0.001" value={l.countedWeight} onChange={e=>update(l.id,'countedWeight',e.target.value)}/></td><td className={Math.abs(Number(l.weightDifference))>.0005?'text-danger':''}>{l.weightDifference}</td><td><input className="table-input" value={l.reason||''} onChange={e=>update(l.id,'reason',e.target.value)} placeholder={Math.abs(Number(l.weightDifference))>.0005||Number(l.quantityDifference)!==0?'مطلوب':'—'}/></td></tr>)}</tbody></table></div><label className="field mt"><span>ملاحظات الجرد</span><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="totals"><div><span>عدد الفروقات</span><b>{diffs.length}</b></div><div><span>إجمالي فرق الوزن</span><b>{diffs.reduce((s,l)=>s+Number(l.weightDifference||0),0).toFixed(3)} غ</b></div></div><button className="btn primary wide">اعتماد وحفظ الجرد أوفلاين</button></form></div>}
  </>
}
